---
title: "Ch2 Geographic Data in R"
output: html_notebook
---

# Introduction

## Libraries

```{r, include=FALSE}
source("../code/before_script.R")

```

```{r}
library(sf)
library(terra)
library(spData)
library(spDataLarge)
```

## Off-line documentation

```{r}
vignette(package = "sf")
vignette("sf1")
```

```{r}
class(world)
names(world)
```

```{r}
str(world)
```

```{r}
plot(world)
```

```{r}
summary(world["lifeExp"])
```

```{r}
world_mini <- world[1:2, 1:3]
world_mini
```

# Vector Data

## Simple Features

```{r}
world_dfr <- st_read(system.file("shapes/world.shp",
                                 package = "spData"))
```

```{r}
world_table <- read_sf(system.file("shapes/world.shp",
                                 package = "spData"))
class(world_table)
class(world_dfr)
```

## Basic map making

```{r sfplot, fig.cap="Plotting with sf, with multiple variables (left) and a single variable (right).", out.width="49%", fig.show='hold', warning=FALSE, fig.scap="Plotting with sf."}
plot(world[3:6])
plot(world["pop"])
```

**Adding layers**

```{r}
world_asia <- world[world$continent == "Asia",]
asia <- st_union(world_asia)
```

```{r}
plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "green")
```

### Example overlaying circles for population

```{r warning=FALSE}
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE)
plot(st_geometry(world_cents), add = TRUE, cex = cex)
```

```{r}
india = world[world$name_long == "India",]
plot(st_geometry(india), expandBB = c(0 ,0.2 ,0.1 ,1), col = "gray", lwd = 3)
plot(st_geometry(world_asia), add = TRUE)
```

## sf class

```{r}
lnd_point = st_point(c(0.1, 51.5))                 # sfg object
lnd_geom = st_sfc(lnd_point, crs = "EPSG:4326")    # sfc object
lnd_attrib = data.frame(                           # data.frame object
  name = "London",
  temperature = 25,
  date = as.Date("2023-06-21")
)
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom)    # sf object
lnd_sf
```

```{r}
class(lnd_sf)
```

```{r}
sf_use_s2()
```

```{r}
india_buffer_with_s2 = st_buffer(india, 1) # 1 meter
sf_use_s2(FALSE)
india_buffer_without_s2 = st_buffer(india, 1)
sf_use_s2(TRUE)
```

# Raster Data

```{r}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
my_rast = rast(raster_filepath)
class(my_rast)
```

```{r}
my_rast
```

```{r}
plot(my_rast)
```

```{r}
single_raster_file = system.file("raster/srtm.tif", package = "spDataLarge")
single_rast = rast(raster_filepath)
```

```{r}
new_raster = rast(nrows = 6, ncols = 6, 
                  xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
                  vals = 1:36)
```

```{r}
multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
multi_rast = rast(multi_raster_file)
multi_rast
```

```{r}
nlyr(multi_rast)
```

## Layer selection

```{r}
multi_rast3 = subset(multi_rast, 3)
multi_rast4 = subset(multi_rast, "landsat_4")
multi_rast34 = c(multi_rast3, multi_rast4)
```

# Coordinate Reference Systems

# Units

```{r}
luxembourg <- world[world$name_long == "Luxembourg",]
st_area(luxembourg)
```

**bad**

```{r}
st_area(luxembourg) / 1e6
```

**instead**

```{r}
units::set_units(st_area(luxembourg), km^2)
```

```{r}
res(my_rast)
```

```{r}
repr <- project(my_rast, "EPSG:26912")
res(repr)
```
